/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcuraengine_JCuraEngine */

#ifndef _Included_org_jcuraengine_JCuraEngine
#define _Included_org_jcuraengine_JCuraEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcuraengine_JCuraEngine
 * Method:    jniNewJCuraEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jcuraengine_JCuraEngine_jniNewJCuraEngine
  (JNIEnv *, jobject);

/*
 * Class:     org_jcuraengine_JCuraEngine
 * Method:    jniDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jcuraengine_JCuraEngine_jniDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jcuraengine_JCuraEngine
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jcuraengine_JCuraEngine_test
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
